-- ============================================================
-- DEPRECATED: use the versioned migrations under ./supabase/migrations
-- ============================================================
--
-- This repository now treats the local Supabase CLI project as the source
-- of truth for schema changes. Do not edit the database manually from this
-- file during normal development.
--
-- Development workflow:
--   1. supabase start
--   2. supabase db reset
--   3. Review and evolve SQL in ./supabase/migrations
--   4. Use ./supabase/seed.sql for deterministic local test data
--
-- Current baseline migration:
--   ./supabase/migrations/202605070001_phase1_foundation.sql
--
-- If you must inspect the schema manually in Supabase Studio or the SQL
-- editor, read the migration file above rather than maintaining a second,
-- divergent copy here.
-- ============================================================
